const AppControlConfig = require("../models/AppControlConfig");
const AppControlItem = require("../models/AppControlItem");
const AdminActivity = require("../models/AdminActivity");
const Service = require("../models/Service");
const Partner = require("../models/Partner");
const FeatureRegistry = require("../models/FeatureRegistry");
const { emitAdminEvent } = require("../sockets/bookingSocket");
const { normalizeConfig, getPublicAppControlConfig, invalidatePublishedConfig, normalizedApp } = require("../utils/appControl");
const { normalizeServiceCategory, serviceCatalog, serviceCategoryVariants } = require("../utils/serviceCategory");

function targetApp(req) { return normalizedApp(req.query?.app || req.body?.app); }
function configKey(req) { return `${targetApp(req)}-app`; }
function actor(req) { return String(req.auth?.email || req.headers["x-admin-actor"] || "admin").slice(0, 160); }
function isObject(value) { return value && typeof value === "object" && !Array.isArray(value); }
function contentFilter(app) { return app === "customer" ? { $or: [{ app: "customer" }, { app: { $exists: false } }] } : { app: "partner" }; }
function assertSuperAdmin(req) { if (req.authType === "admin_jwt" && req.adminProfile?.role !== "super_admin") { const error = new Error("Only a Super Admin can change App Control Center settings"); error.status = 403; throw error; } }
function merge(base, patch) { const output = { ...(isObject(base) ? base : {}) }; for (const [name, value] of Object.entries(isObject(patch) ? patch : {})) output[name] = isObject(value) ? merge(output[name], value) : value; return output; }
function itemPayload(body) { const fields = ["title", "message", "imageUrl", "ctaText", "ctaAction", "serviceCategory", "placement", "priority", "audience", "startsAt", "endsAt"]; const output = Object.fromEntries(fields.filter((field) => Object.hasOwn(body || {}, field)).map((field) => [field, body[field]])); const start = output.startsAt ? new Date(output.startsAt).getTime() : -Infinity; const end = output.endsAt ? new Date(output.endsAt).getTime() : Infinity; if (Number.isNaN(start) || Number.isNaN(end) || start > end) { const error = new Error("End time must be after start time"); error.status = 400; throw error; } return output; }
async function audit(req, eventName, title, detail, payload = {}) { await AdminActivity.create({ eventName, category: "app_control", title, detail, actorRole: "admin", actorName: actor(req), status: "success", payload: { ...payload, app: targetApp(req) } }); }
function broadcast(req, eventName, payload = {}) { emitAdminEvent(eventName, { app: targetApp(req), ...payload }); }

const customerFeatures = [
  ["home_banners", "Home banners & announcements", "Shows published banners and announcements on the customer home screen."],
  ["booking_history", "Booking history", "Lets customers access existing booking history."],
  ["commercial_services", "Commercial services", "Shows the commercial services entry point on the customer home screen."]
];
const partnerFeatures = [
  ["partner_dashboard", "Partner dashboard", "Partner home dashboard"], ["partner_booking_management", "Booking management", "View and manage assigned bookings"], ["partner_earnings", "Earnings", "Partner earnings and payout views"], ["partner_availability", "Availability", "Online availability controls"], ["partner_profile", "Profile", "Partner profile and account details"], ["partner_notifications", "Notifications", "Partner notification center"], ["partner_support", "Support", "Partner help and support"], ["partner_location", "Live location", "Partner location updates"], ["partner_documents", "Document management", "Partner document and KYC flows"]
];
async function featureRegistry(app) { const source = app === "partner" ? partnerFeatures : customerFeatures; await Promise.all(source.map(([featureId, name, description]) => FeatureRegistry.updateOne({ featureId }, { $setOnInsert: { featureId, name, description, app }, $set: { app, implementationState: "active", remoteConfigSupported: true, lastDiscoveredAt: new Date() } }, { upsert: true }))); return FeatureRegistry.find({ app }).sort({ name: 1 }).lean(); }
function validKind(req) { const kind = String(req.params.kind || ""); if (!["announcement", "banner"].includes(kind) || (targetApp(req) === "partner" && kind === "banner")) { const error = new Error("Unknown content type"); error.status = 404; throw error; } return kind; }

function mergedCustomerServices(databaseServices) {
  const catalog = serviceCatalog();
  const recordsByCategory = new Map(
    databaseServices.map((service) => [normalizeServiceCategory(service.serviceCategory || service.name), service])
  );
  const catalogCategories = new Set(catalog.map((service) => service.serviceCategory));
  const catalogServices = catalog.map((service) => {
    const databaseService = recordsByCategory.get(service.serviceCategory);
    return databaseService
      ? { ...service, ...databaseService, serviceCategory: service.serviceCategory }
      : {
        _id: `catalog:${service.serviceCategory}`,
        ...service,
        isActive: true,
        availability: "AVAILABLE",
        availabilityMessage: "",
        availabilityStartsAt: null,
        availabilityEndsAt: null
      };
  });
  const additionalServices = databaseServices.filter((service) => !catalogCategories.has(normalizeServiceCategory(service.serviceCategory || service.name)));
  return [...catalogServices, ...additionalServices];
}

async function publicConfig(req, res, next) { try { const app = normalizedApp(req.query.app); res.set("Cache-Control", "no-store, max-age=0"); return res.json(await getPublicAppControlConfig(app === "partner" ? "partners" : "users", app)); } catch (error) { return next(error); } }
async function overview(req, res, next) { try { const app = targetApp(req); const doc = await AppControlConfig.findOne({ key: configKey(req) }).lean(); const filter = contentFilter(app); const [announcements, banners, auditLogs, databaseServices, features, activePartners] = await Promise.all([AppControlItem.countDocuments({ ...filter, kind: "announcement", status: { $in: ["published", "scheduled"] } }), app === "partner" ? 0 : AppControlItem.countDocuments({ ...filter, kind: "banner", status: { $in: ["published", "scheduled"] } }), AdminActivity.countDocuments({ category: "app_control", "payload.app": app }), app === "customer" ? Service.find({}, { serviceCategory: 1, name: 1, description: 1, isActive: 1, availability: 1, availabilityMessage: 1, availabilityStartsAt: 1, availabilityEndsAt: 1 }).sort({ name: 1 }).limit(250).lean() : [], featureRegistry(app), app === "partner" ? Partner.countDocuments({ accountStatus: "active" }) : 0]); return res.json({ app, draft: normalizeConfig(doc?.draft), published: normalizeConfig(doc?.published), version: Number(doc?.version || 0), updatedAt: doc?.updatedAt || null, publishedAt: doc?.publishedAt || null, publishedBy: doc?.publishedBy || "", counts: { announcements, banners, auditLogs, activePartners }, services: app === "customer" ? mergedCustomerServices(databaseServices) : [], features }); } catch (error) { return next(error); } }
async function saveDraft(req, res, next) { try { assertSuperAdmin(req); const section = String(req.body?.section || "").trim(); let patch = req.body?.value; if (!section || !isObject(patch)) return res.status(400).json({ message: "section and object value are required" }); if (targetApp(req) === "partner" && ["launch", "services"].includes(section)) return res.status(400).json({ message: "This control is not supported for the Partner App" }); if (section === "services") { const knownCategories = new Set(serviceCatalog().map((service) => service.serviceCategory)); const normalizedEntries = Object.entries(patch).map(([category, value]) => [normalizeServiceCategory(category), value]); if (normalizedEntries.some(([category]) => !knownCategories.has(category))) return res.status(400).json({ message: "Only implemented customer services can be controlled" }); patch = Object.fromEntries(normalizedEntries); } if (section === "update") { for (const field of ["latestVersion", "minimumVersion"]) { const value = String(patch[field] || "").trim(); if (value && !/^\d+(?:\.\d+){1,3}$/.test(value)) return res.status(400).json({ message: `${field === "latestVersion" ? "Latest version" : "Minimum supported version"} must use numbers such as 1.2.0` }); } } const current = await AppControlConfig.findOne({ key: configKey(req) }).lean(); const draft = normalizeConfig(merge(current?.draft, { [section]: patch })); const updated = await AppControlConfig.findOneAndUpdate({ key: configKey(req) }, { $set: { draft, updatedBy: actor(req) } }, { upsert: true, new: true, setDefaultsOnInsert: true }); await audit(req, "app_control:draft_saved", "Draft saved", section, { section }); broadcast(req, "app_control:draft_saved", { section }); return res.json({ draft: normalizeConfig(updated.draft), updatedAt: updated.updatedAt }); } catch (error) { return next(error); } }
async function publish(req, res, next) { try { assertSuperAdmin(req); const app = targetApp(req); const current = await AppControlConfig.findOne({ key: configKey(req) }); if (!current) return res.status(409).json({ message: "Save a draft before publishing" }); const previous = normalizeConfig(current.published); const published = normalizeConfig(current.draft); current.published = published; current.publishedAt = new Date(); current.publishedBy = actor(req); current.updatedBy = actor(req); current.version = Number(current.version || 0) + 1; await current.save(); if (app === "customer") await Promise.all(Object.entries(published.services).map(([serviceCategory, value]) => Service.updateMany({ serviceCategory: { $in: serviceCategoryVariants(serviceCategory) } }, { $set: { availability: value.status, availabilityMessage: value.message, availabilityStartsAt: value.startsAt || null, availabilityEndsAt: value.endsAt || null } }))); await AppControlItem.updateMany({ ...contentFilter(app), status: { $in: ["draft", "scheduled"] } }, { $set: { status: "published", updatedBy: actor(req) } }); invalidatePublishedConfig(app); await audit(req, "app_control:published", "Configuration published", `${app} application configuration updated`, { previous, published, version: current.version }); broadcast(req, "app_control:published", { version: current.version }); return res.json({ ok: true, version: current.version, published, publishedAt: current.publishedAt }); } catch (error) { return next(error); } }
async function openBookings(req, res, next) { try { assertSuperAdmin(req); if (targetApp(req) !== "customer") return res.status(400).json({ message: "Opening customer bookings is not a Partner App control" }); const current = await AppControlConfig.findOne({ key: configKey(req) }); const previous = normalizeConfig(current?.published); const published = normalizeConfig(merge(current?.draft, { appStatus: { mode: "LIVE" }, launch: { enabled: false } })); const updated = await AppControlConfig.findOneAndUpdate({ key: configKey(req) }, { $set: { draft: published, published, publishedAt: new Date(), publishedBy: actor(req), updatedBy: actor(req) }, $inc: { version: 1 } }, { upsert: true, new: true, setDefaultsOnInsert: true }); invalidatePublishedConfig("customer"); await audit(req, "app_control:bookings_opened", "Launch screen removed", "Customer booking flow opened manually", { previous, published, version: updated.version }); broadcast(req, "app_control:published", { version: updated.version }); return res.json({ ok: true, version: updated.version, published }); } catch (error) { return next(error); } }
async function rollback(req, res, next) { try { assertSuperAdmin(req); const app = targetApp(req); const activity = await AdminActivity.findOne({ _id: req.params.activityId, category: "app_control", eventName: "app_control:published", "payload.app": app }).lean(); if (!activity?.payload?.previous) return res.status(404).json({ message: "Published configuration snapshot not found" }); const restored = normalizeConfig(activity.payload.previous); const current = await AppControlConfig.findOneAndUpdate({ key: configKey(req) }, { $set: { draft: restored, published: restored, publishedAt: new Date(), publishedBy: actor(req), updatedBy: actor(req) }, $inc: { version: 1 } }, { upsert: true, new: true, setDefaultsOnInsert: true }); invalidatePublishedConfig(app); await audit(req, "app_control:rolled_back", "Configuration rolled back", `Restored snapshot from ${activity.createdAt.toISOString()}`, { restoredFrom: String(activity._id), published: restored, version: current.version }); broadcast(req, "app_control:published", { version: current.version }); return res.json({ ok: true, version: current.version, published: restored }); } catch (error) { return next(error); } }
async function saveServiceAvailability(req, res, next) { try { assertSuperAdmin(req); if (targetApp(req) !== "customer") return res.status(400).json({ message: "Service availability is a Customer App control" }); const category = normalizeServiceCategory(req.params.category); if (!category || category.length > 80 || !serviceCatalog().some((service) => service.serviceCategory === category)) return res.status(400).json({ message: "A valid implemented service category is required" }); const config = normalizeConfig({ services: { [category]: req.body || {} } }).services[category]; const current = await AppControlConfig.findOne({ key: configKey(req) }).lean(); const draft = normalizeConfig(merge(current?.draft, { services: { [category]: config } })); await AppControlConfig.findOneAndUpdate({ key: configKey(req) }, { $set: { draft, updatedBy: actor(req) } }, { upsert: true, new: true, setDefaultsOnInsert: true }); await audit(req, "service:availability_saved", "Service availability saved", `${category}: ${config.status}`, { category, ...config }); return res.json({ category, config, draft }); } catch (error) { return next(error); } }
async function resetDraft(req, res, next) { try { assertSuperAdmin(req); const current = await AppControlConfig.findOne({ key: configKey(req) }); if (!current) return res.json({ ok: true, draft: normalizeConfig({}) }); current.draft = normalizeConfig(current.published); current.updatedBy = actor(req); await current.save(); await audit(req, "app_control:draft_reset", "Draft reset", "Draft restored to published configuration"); return res.json({ ok: true, draft: normalizeConfig(current.draft) }); } catch (error) { return next(error); } }
async function listItems(req, res, next) { try { const kind = validKind(req); const app = targetApp(req); const status = String(req.query.status || ""); const search = String(req.query.search || "").trim(); const filter = { ...contentFilter(app), kind, ...(status ? { status } : {}), ...(search ? { title: new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i") } : {}) }; const items = await AppControlItem.find(filter).sort({ priority: 1, createdAt: -1 }).limit(Math.min(Number(req.query.limit || 100), 250)).lean(); return res.json({ items, now: new Date().toISOString() }); } catch (error) { return next(error); } }
async function createItem(req, res, next) { try { assertSuperAdmin(req); const kind = validKind(req); const body = itemPayload(req.body); if (!String(body.title || "").trim()) return res.status(400).json({ message: "Title is required" }); const item = await AppControlItem.create({ ...body, app: targetApp(req), kind, status: "draft", createdBy: actor(req), updatedBy: actor(req) }); await audit(req, `${kind}:created`, `${kind} created`, item.title, { id: String(item._id) }); return res.status(201).json({ item }); } catch (error) { return next(error); } }
async function updateItem(req, res, next) { try { assertSuperAdmin(req); const kind = validKind(req); const item = await AppControlItem.findOneAndUpdate({ _id: req.params.id, kind, ...contentFilter(targetApp(req)) }, { $set: { ...itemPayload(req.body), status: "draft", updatedBy: actor(req) } }, { new: true, runValidators: true }); if (!item) return res.status(404).json({ message: "Content not found" }); await audit(req, `${kind}:updated`, `${kind} updated`, item.title, { id: String(item._id) }); return res.json({ item }); } catch (error) { return next(error); } }
async function deleteItem(req, res, next) { try { assertSuperAdmin(req); const item = await AppControlItem.findOneAndDelete({ _id: req.params.id, kind: req.params.kind, ...contentFilter(targetApp(req)) }); if (!item) return res.status(404).json({ message: "Content not found" }); await audit(req, `${item.kind}:deleted`, `${item.kind} deleted`, item.title, { id: String(item._id) }); return res.json({ ok: true }); } catch (error) { return next(error); } }
async function auditLogs(req, res, next) { try { const limit = Math.min(Math.max(Number(req.query.limit || 50), 1), 250); const logs = await AdminActivity.find({ category: "app_control", "payload.app": targetApp(req) }).sort({ createdAt: -1 }).limit(limit).lean(); return res.json({ logs }); } catch (error) { return next(error); } }
module.exports = { publicConfig, overview, saveDraft, publish, openBookings, rollback, resetDraft, saveServiceAvailability, listItems, createItem, updateItem, deleteItem, auditLogs };
