const AppControlConfig = require("../models/AppControlConfig");
const AppControlItem = require("../models/AppControlItem");
const AdminActivity = require("../models/AdminActivity");
const Service = require("../models/Service");
const { normalizeConfig, getPublicAppControlConfig, invalidatePublishedConfig, isScheduleActive } = require("../utils/appControl");

function actor(req) { return String(req.auth?.email || req.headers["x-admin-actor"] || "admin").slice(0, 160); }
function isObject(value) { return value && typeof value === "object" && !Array.isArray(value); }
function itemPayload(body) { const allowed = ["title", "message", "imageUrl", "ctaText", "ctaAction", "serviceCategory", "placement", "priority", "audience", "status", "startsAt", "endsAt"]; const output = Object.fromEntries(allowed.filter((key) => Object.prototype.hasOwnProperty.call(body || {}, key)).map((key) => [key, body[key]])); const start = output.startsAt ? new Date(output.startsAt).getTime() : -Infinity; const end = output.endsAt ? new Date(output.endsAt).getTime() : Infinity; if (Number.isNaN(start) || Number.isNaN(end) || start > end) { const error = new Error("End time must be after start time"); error.status = 400; throw error; } return output; }
function merge(base, patch) { const out = { ...(isObject(base) ? base : {}) }; for (const [key, value] of Object.entries(isObject(patch) ? patch : {})) out[key] = isObject(value) ? merge(out[key], value) : value; return out; }
async function audit(req, eventName, title, detail, payload = {}) { await AdminActivity.create({ eventName, category: "app_control", title, detail, actorRole: "admin", actorName: actor(req), status: "success", payload }); }

async function publicConfig(req, res, next) { try { const audience = ["users", "partners"].includes(String(req.query.audience || "")) ? req.query.audience : "users"; res.set("Cache-Control", "private, max-age=10"); return res.json(await getPublicAppControlConfig(audience)); } catch (error) { return next(error); } }

async function overview(_req, res, next) { try { const doc = await AppControlConfig.findOne({ key: "customer-app" }).lean(); const [announcements, banners, auditLogs, services] = await Promise.all([AppControlItem.countDocuments({ kind: "announcement", status: { $in: ["published", "scheduled"] } }), AppControlItem.countDocuments({ kind: "banner", status: { $in: ["published", "scheduled"] } }), AdminActivity.countDocuments({ category: "app_control" }), Service.find({}, { serviceCategory: 1, name: 1, description: 1, isActive: 1, availability: 1, availabilityMessage: 1, availabilityStartsAt: 1, availabilityEndsAt: 1 }).sort({ name: 1 }).limit(250).lean()]); return res.json({ draft: normalizeConfig(doc?.draft), published: normalizeConfig(doc?.published), version: Number(doc?.version || 0), updatedAt: doc?.updatedAt || null, counts: { announcements, banners, auditLogs }, services }); } catch (error) { return next(error); } }

async function saveDraft(req, res, next) { try { const section = String(req.body?.section || "").trim(); const patch = req.body?.value; if (!section || !isObject(patch)) return res.status(400).json({ message: "section and object value are required" }); const current = await AppControlConfig.findOne({ key: "customer-app" }).lean(); const draft = normalizeConfig(merge(current?.draft, { [section]: patch })); const updated = await AppControlConfig.findOneAndUpdate({ key: "customer-app" }, { $set: { draft, updatedBy: actor(req) } }, { upsert: true, new: true, setDefaultsOnInsert: true }); await audit(req, "app_control:draft_saved", "Draft saved", section, { section }); return res.json({ draft: normalizeConfig(updated.draft), updatedAt: updated.updatedAt }); } catch (error) { return next(error); } }

async function publish(req, res, next) { try { const current = await AppControlConfig.findOne({ key: "customer-app" }); if (!current) return res.status(409).json({ message: "Save a draft before publishing" }); const previous = normalizeConfig(current.published); const published = normalizeConfig(current.draft); current.published = published; current.publishedAt = new Date(); current.publishedBy = actor(req); current.updatedBy = actor(req); current.version = Number(current.version || 0) + 1; await current.save(); await Promise.all(Object.entries(published.services).map(([serviceCategory, item]) => Service.updateMany({ serviceCategory }, { $set: { availability: item.status, availabilityMessage: item.message, availabilityStartsAt: item.startsAt || null, availabilityEndsAt: item.endsAt || null } }))); invalidatePublishedConfig(); await audit(req, "app_control:published", "Configuration published", "Customer application configuration updated", { previous, published, version: current.version }); return res.json({ ok: true, version: current.version, published, publishedAt: current.publishedAt }); } catch (error) { return next(error); } }

async function rollback(req, res, next) { try { const activity = await AdminActivity.findOne({ _id: req.params.activityId, category: "app_control", eventName: "app_control:published" }).lean(); if (!activity?.payload?.previous) return res.status(404).json({ message: "Published configuration snapshot not found" }); const restored = normalizeConfig(activity.payload.previous); const current = await AppControlConfig.findOneAndUpdate({ key: "customer-app" }, { $set: { draft: restored, published: restored, publishedAt: new Date(), publishedBy: actor(req), updatedBy: actor(req) }, $inc: { version: 1 } }, { upsert: true, new: true, setDefaultsOnInsert: true }); invalidatePublishedConfig(); await audit(req, "app_control:rolled_back", "Configuration rolled back", `Restored snapshot from ${activity.createdAt.toISOString()}`, { restoredFrom: String(activity._id), published: restored, version: current.version }); return res.json({ ok: true, version: current.version, published: restored }); } catch (error) { return next(error); } }

async function saveServiceAvailability(req, res, next) { try { const category = String(req.params.category || "").trim().toLowerCase(); if (!category || category.length > 80) return res.status(400).json({ message: "A valid service category is required" }); const patch = req.body || {}; const config = normalizeConfig({ services: { [category]: patch } }).services[category]; await Service.updateMany({ serviceCategory: category }, { $set: { availability: config.status, availabilityMessage: config.message, availabilityStartsAt: config.startsAt || null, availabilityEndsAt: config.endsAt || null } }); const current = await AppControlConfig.findOne({ key: "customer-app" }).lean(); const draft = normalizeConfig(merge(current?.draft, { services: { [category]: config } })); await AppControlConfig.findOneAndUpdate({ key: "customer-app" }, { $set: { draft, updatedBy: actor(req) } }, { upsert: true, new: true, setDefaultsOnInsert: true }); await audit(req, "service:availability_saved", "Service availability saved", `${category}: ${config.status}`, { category, ...config }); return res.json({ category, config, draft }); } catch (error) { return next(error); } }

async function resetDraft(req, res, next) { try { const current = await AppControlConfig.findOne({ key: "customer-app" }); if (!current) return res.json({ ok: true, draft: normalizeConfig({}) }); current.draft = normalizeConfig(current.published); current.updatedBy = actor(req); await current.save(); await audit(req, "app_control:draft_reset", "Draft reset", "Draft restored to the published configuration"); return res.json({ ok: true, draft: normalizeConfig(current.draft) }); } catch (error) { return next(error); } }

async function listItems(req, res, next) { try { const kind = String(req.params.kind || ""); if (!["announcement", "banner"].includes(kind)) return res.status(404).json({ message: "Unknown content type" }); const status = String(req.query.status || ""); const search = String(req.query.search || "").trim(); const filter = { kind, ...(status ? { status } : {}), ...(search ? { title: new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i") } : {}) }; const items = await AppControlItem.find(filter).sort({ priority: 1, createdAt: -1 }).limit(Math.min(Number(req.query.limit || 100), 250)).lean(); return res.json({ items, now: new Date().toISOString() }); } catch (error) { return next(error); } }

async function createItem(req, res, next) { try { const kind = String(req.params.kind || ""); if (!["announcement", "banner"].includes(kind)) return res.status(404).json({ message: "Unknown content type" }); const body = itemPayload(req.body); if (!String(body.title || "").trim()) return res.status(400).json({ message: "Title is required" }); const item = await AppControlItem.create({ ...body, kind, createdBy: actor(req), updatedBy: actor(req) }); await audit(req, `${kind}:created`, `${kind} created`, item.title, { id: String(item._id) }); return res.status(201).json({ item }); } catch (error) { return next(error); } }

async function updateItem(req, res, next) { try { const kind = String(req.params.kind || ""); const item = await AppControlItem.findOneAndUpdate({ _id: req.params.id, kind }, { $set: { ...itemPayload(req.body), updatedBy: actor(req) } }, { new: true, runValidators: true }); if (!item) return res.status(404).json({ message: "Content not found" }); await audit(req, `${kind}:updated`, `${kind} updated`, item.title, { id: String(item._id) }); return res.json({ item }); } catch (error) { return next(error); } }

async function deleteItem(req, res, next) { try { const item = await AppControlItem.findOneAndDelete({ _id: req.params.id, kind: req.params.kind }); if (!item) return res.status(404).json({ message: "Content not found" }); await audit(req, `${item.kind}:deleted`, `${item.kind} deleted`, item.title, { id: String(item._id) }); return res.json({ ok: true }); } catch (error) { return next(error); } }

async function auditLogs(req, res, next) { try { const limit = Math.min(Math.max(Number(req.query.limit || 50), 1), 250); const logs = await AdminActivity.find({ category: "app_control" }).sort({ createdAt: -1 }).limit(limit).lean(); return res.json({ logs }); } catch (error) { return next(error); } }

module.exports = { publicConfig, overview, saveDraft, publish, rollback, resetDraft, saveServiceAvailability, listItems, createItem, updateItem, deleteItem, auditLogs };
